### ISSUE TITLE
Missing Chinese languages support

### ISSUE THREAD

**Issue by denis-stepushchik** [aloisdeniel/flutter_csv_localization#1]
Hi, thanks for great tool! Can you add support for Chinese languages? 

supportedLocales: [
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'), // generic simplified Chinese 'zh_Hans'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'), // generic traditional Chinese 'zh_Hant'
],

**Comment by aloisdeniel** [comment]
Ah thanks for the proposal ! 

I will add the possibility to have `zh(Hans)`.

**Comment by aloisdeniel** [comment]
Okay I published the version `0.3.0` that should support countryCode and scriptCode !

Not tested a lot yet, so let me know if it works for you !

Examples :
* `fr` : one value with <language>
* `en-US` : two values with <language>-<country> 
* `zh-Hans-CN` : three values with <language>-<script>-<country>

**Comment by denis-stepushchik** [comment]
@aloisdeniel thank you a lot for this update!
I have some issue with delegate I will create PR soon.

**Comment by denis-stepushchik** [comment]
Sorry, can not create PR (I do not have permissions for pushing new branch).

The issue is in isSupported method. Now we have next implementation:
`@override
  bool isSupported(Locale locale) =>
      AppLocalizations.languages.containsKey(locale.countryCode)`
But in languages map we have 'Locale' as a key.
So need to change this method to 
`@override
  bool isSupported(Locale locale) =>
      AppLocalizations.languages.containsKey(locale);`

Could you please add this small update?

**Comment by aloisdeniel** [comment]
Yeah, forgot that part. Merged and published !

**Comment by denis-stepushchik** [comment]
@aloisdeniel Thank you for a quick responses! Your tool helped me a lot!
